version: '3.3'

services:

  #  Nginx latest version
  webserver:
    image: webserver:latest
    ports:
      - ${IP}:${WP_PORT}:80
    volumes:
      - ./uptarget-co:/usr/share/nginx/html

    working_dir: /var/www/html
    restart: always

